---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template to create a Lambda function which triggers
  every time S3 delete bucket call is made. The function will empty the bucket.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: Template Definition
      Parameters:
    #     - Name
    #     - Description
        - Environment
    #     - InstanceType
    - Label:
        Default: Stack Tagging
      Parameters:
        - CreatedBy
Parameters:
  # Name:
  #   Type: String
  #   Description: 'Enter name for Cloud 9 Environment'
  #   Default: Playground
  Environment: 
    Type: String
    Description: 'What environment is this Cloud 9 Environment for?'
    Default: NONPROD
    AllowedValues: 
      - NONPROD
      - PROD
      - OAT
    ConstraintDescription: 'Choose an environment to create the resource in.'
  # InstanceType: 
  #   Type: String
  #   Description: 'Choose an instance type for Cloud 9 Environment'
  #   Default: t2.micro
  #   AllowedValues: 
  #     - t2.micro
  #     - t3.small
  #     - m5.large
  CreatedBy:
    Type: String
    Description: 'Who executed this script'
    Default: System
Resources: 
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "s3:*"
            Resource: "*"
          - Effect: Allow
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource: "*"

  EmptyS3BucketLambda: 
    Type: "AWS::Lambda::Function"
    Properties: 
      Handler: "index.handler"
      Role: 
        Fn::GetAtt: 
          - "LambdaExecutionRole"
          - "Arn"
      Runtime: "python3.7"
      Timeout: 600 # timeout is large allowing enough time for bucket to empty
      Code: 
        ZipFile: |
          #!/usr/bin/env python
          # -*- coding: utf-8 -*-
          import json
          import boto3
          from botocore.vendored import requests

          def handler(event, context):
              try:
                  bucket = event['ResourceProperties']['BucketName']

                  if event['RequestType'] == 'Delete':
                      s3 = boto3.resource('s3')
                      bucket = s3.Bucket(bucket)
                      for obj in bucket.objects.filter():
                          s3.Object(bucket.name, obj.key).delete()

                  sendResponseCfn(event, context, "SUCCESS")
              except Exception as e:
                  print(e)
                  sendResponseCfn(event, context, "FAILED")


          def sendResponseCfn(event, context, responseStatus):
              response_body = {'Status': responseStatus,
                              'Reason': 'Log stream name: ' + context.log_stream_name,
                              'PhysicalResourceId': context.log_stream_name,
                              'StackId': event['StackId'],
                              'RequestId': event['RequestId'],
                              'LogicalResourceId': event['LogicalResourceId'],
                              'Data': json.loads("{}")}

              requests.put(event['ResponseURL'], data=json.dumps(response_body))

Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  LambdaFunctionARN:
    Description: 'The ARN of the Lambda function that empties an S3 bucket'
    Value: !GetAtt EmptyS3BucketLambda.Arn
    Export:
      Name: EmptyS3BucketLambda
